name: Netpal
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#include: ['_summaries']
include: ['_walkthroughs', '_summaries', '_images', '_challenges', 'resources', '_CheatSheets']
kramdown:
  parse_block_html: true

